### PR TITLE
feat: streams

### LINKED ISSUE #50: Allow stdout/stderr streams
Allowing logger to stream to stdout & stderr is essentially to capturing logs when running in containerised environments.

### PR DESCRIPTION
**Pull request by adamkdean**
This PR allows the use of streams, either [configurable libraries](https://github.com/trentm/node-bunyan/wiki/Awesome-Bunyan#streams) or stream instances, such as `process.stdout`.

Closes #50 

## Usage 

```
const logger = require('@dadi/logger')

const options = {
  enabled: true,
  level: 'info',
  stream: {
    enabled: true,
    instance: process.stdout
  }
}

logger.init(options, {}, process.env.NODE_ENV)
logger.info({ module: 'ImageHandler' }, 'GET: ' + req.url)
```

### CODE REVIEW

**Comment by adamkdean** [comment]
This PR supersedes #52

**Comment by jimlambie** [comment]
@adamkdean I like it. Flexbile. Interestingly, from what I could tell, both of those two methods could be combined (if the end-user desires):

```
const logger = require('@dadi/logger')
const BunyanSlack = require('bunyan-slack')
const bunyanSlack = new BunyanSlack({
  "webhook_url": "https://hooks.slack.com/services/...",
  "channel": "#channel-name"
})

const options = {
  enabled: true,
  level: 'info',
  stream: {
    enabled: true,
    instance: bunyanSlack
  }
}
```

Do you agree?

**Comment by adamkdean** [comment]
@jimlambie yes that's correct. If the user wanted to pass an instance of stream, they could initialise one as you have shown, but in the case that they wish to use configuration, e.g. with API, then being able to pass the stream library is also an option.

**Comment by adamkdean** [comment]
@eduardoboucas if you have a moment, could you give this PR a once over?

**Comment by adamkdean** [comment]
🙇 Thanks!

**Pull request merged**
